user route
jhchoi0830/compcar_service pull request #9
Opened 2022-12-03 17:42 UTC by jhchoi0830

2022-12-04 18:36 UTC, nhistory reviewed
There are no endpoints in user_routes.py

2022-12-04 18:36 UTC, nhistory commented on app/endpoints/car_routes.py
> +from app.models.usedCarModel import UsedCar
Model naming convention
- UsedCarModel

2022-12-04 18:36 UTC, nhistory commented on app/endpoints/car_routes.py
> +from app.models.userModel import User
Model naming conventions
- UserModel

2022-12-09 02:01 UTC, aurora-yn requested changes

2022-12-09 02:01 UTC, aurora-yn commented on app/endpoints/car_routes.py
> +from app.models.usedCarModel import UsedCar
This is a file path. For the model, PascalCase is the correct convention. 
Not to break local server `usedCarModel` change is a right update. But, its file should be lower cases with underscores. I have made changes in my PR here: https://github.com/jhchoi0830/compcar_service/pull/12
After merging 12th PR, please update this branch `ENDPOINT-USERROUTE` before merge!

Let me know if you need help.

2022-12-09 02:01 UTC, aurora-yn commented on app/endpoints/user_routes.py
> +@router.get("/")
Root endpoint already exist at `car_routes.py`. No needed in this route file.

2022-12-09 02:01 UTC, aurora-yn commented on app/endpoints/user_routes.py
> +@router.get("/api/car")
Please remove `/api/car` endpoint

2022-12-09 02:01 UTC, aurora-yn commented on app/endpoints/user_routes.py
> +@router.get("/register/user/email/{email}", response_model=list[User])
We will need POST method. Something like:
```
from app.services.database import create_user

@router.post('/api/user/register', response_model=User)
async def post_user(user: User):
    response = await create_user(user.dict())
    if response:
        return response
    raise HTTPException(400, "Something went wrong")

```
Also, please make sure if `user` collection is set in MongoDB.

2022-12-09 02:01 UTC, aurora-yn commented on app/services/database.py
> +
We will need `create_user`.
Base structure will be:
```
async def create_user(user: User):
    result = await collection_query.insert_one(user)
    return result
```

2022-12-13 22:34 UTC, closed without merging